### PR TITLE
compeltedallproblemsofweek_1

### PR DESCRIPTION
**Pull request by aayushraghav93**

### CODE REVIEW

**Comment by aryanmishra29** [comment]
HI @aayushraghav93 , rename your week_1 folder to Week_1

**Comment by aayushraghav93** [comment]
Done sir

**Comment by aryanmishra29** [comment]
@aayushraghav93 You have created a new folder Week_1 however most of your submissions are still in the old folder. Move all the submissions to the new folder and delete the old folder.

**Comment by aayushraghav93** [comment]
sorry sir...you can check it now

**Pull request merged**
