### PR TITLE
Week1 problems solved

### PR DESCRIPTION
**Pull request by satyagyasingh**

### CODE REVIEW

**Comment by innogeeks** [comment]
Delete one cpp file from your folder then create pull request

**Comment by satyagyasingh** [comment]
> Delete one cpp file from your folder then create pull request

kindly merge the pr now as I have deleted that file

**Comment by satyagyasingh** [comment]
@innogeeks Kindly merge the PR, I have solved all week1 problems.

**Comment by aryanmishra29** [comment]
Hi @satyagyasingh, kindly submit the solutions only of the problems listed in the Coderspree 3.0 website. (Only 15 of them)
Remove the extra ones and solve the remaining ones.

**Comment by satyagyasingh** [comment]
> Hi @satyagyasingh, kindly submit the solutions only of the problems listed in the Coderspree 3.0 website. (Only 15 of them) Remove the extra ones and solve the remaining ones.

deleted the unwanted file

**Pull request merged**
