### PR TITLE
Submission Added for Week 1

### PR DESCRIPTION
**Pull request by anshv-dev**
i have completed all the problems of week 1.

### CODE REVIEW

**Comment by aryanmishra29** [comment]
@anshv-dev You have changed something in Anant Jaiswal's folder. Undo the changes.

**Comment by anshv-dev** [comment]
I didn't make any changes .

**Comment by aryanmishra29** [comment]
You have added For-Loop.class file in anant's folder.

**Comment by anshv-dev** [comment]
I have deleted the file you can merge it .

**Pull request merged**
