### PR TITLE
CreateMAXMINinanarray.cpp

### PR DESCRIPTION
**Pull request by Shrutichoudhary99**

### CODE REVIEW

**Comment by aryanmishra29** [comment]
Hi @Shrutichoudhary99, kindly remove space from your folder name (Shruti Choudhary -> ShrutiChoudhary), also remove spaces from the names of your submission files.

**Comment by Shrutichoudhary99** [comment]
Done with the changes

**Comment by aryanmishra29** [comment]
@Shrutichoudhary99 you haven't committed any changes. Kindly, sync your fork, pull the code, and then commit and push again.

**Comment by aryanmishra29** [comment]
@Shrutichoudhary99 Kindly remove the spaces from your folder name and the name of your submission file, also solve and submit at least 10 of the 15 problems listed in the coderspree website. We can't accept PR of less than 10 submissions.

**Pull request closed without merging**
