### PR TITLE
Week 1 Problems Solved

### PR DESCRIPTION
**Pull request by praptisharma28**

### CODE REVIEW

**Comment by AdityyaX** [comment]
Hey @praptisharma28 , move all the submissions to the Week_1 folder.

**Comment by praptisharma28** [comment]
Sir @AdityyaX , they are in the week 1 folder. I checked too again.

**Comment by AdityyaX** [comment]
Screenshot 2023-10-10 at 12 02 50 AM

What About this?

**Comment by praptisharma28** [comment]
Oh, OK sir corrected it. Thought you are talking about the folder name.

**Pull request closed without merging**
